name: Benchmark

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # List host CPU info
    - name: Host CPU info
      run: cat /proc/cpuinfo

    # List compiler version
    - name: List compiler version
      run: gcc --version

    # pull and build wolfssl
    - name: Checkout wolfssl
      uses: actions/checkout@v4
      with:
        repository: wolfssl/wolfssl
        path: wolfssl

    # Benchmark with everything enabled
    - name: Benchmark All
      run: cd benchmark && make clean && make WOLFSSL_DIR=../wolfssl DMA=1 && make run
